# Metrics Server Helm chart overrides
# Chart version: 3.13.0 (appVersion 0.8.0)

args:
  - --cert-dir=/tmp
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-use-node-status-port
  - --metric-resolution=15s
  - --secure-port=10250
