name: Frontend CI with Docker Multi-Platform Build

# Principle of least privilege for GITHUB_TOKEN
permissions:
  contents: read
  checks: write # needed for test reporter annotations
  actions: read

concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger on all branches for push events (commits)
  push:
    branches: ["*"]

  # Trigger on pull requests to any branch
  pull_request:
    branches: ["*"]

  # Trigger on merge events (when PR is merged)
  merge_group:
jobs:
  frontend-ci:
    name: Frontend CI Pipeline with Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 1: Install pnpm and Node (ensure pnpm exists before cache logic)
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.0.0
          run_install: false

      - name: Setup Node.js 22 & enable pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies (pnpm)
        run: |
          # If lockfile exists use frozen for reproducibility; else normal install
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile --prefer-offline
          else
            echo "No pnpm-lock.yaml yet – performing non-frozen install (cache still warms)."
            pnpm install --prefer-offline
          fi

      - name: Prepare public env vars for tests (NEXT_PUBLIC_*)
        run: |
          echo "Preparing NEXT_PUBLIC_* variables for test environment..."
          # Try to source from existing example/test env files without exposing secrets
          for candidate in .env.test .env.example .env; do
            if [ -f "$candidate" ]; then
              echo "Scanning $candidate for NEXT_PUBLIC_* entries"
              grep '^NEXT_PUBLIC_' "$candidate" | while IFS='=' read -r k v; do
                if [ -n "$k" ] && [ -n "$v" ]; then
                  echo "Setting $k from $candidate"
                  echo "$k=$v" >> $GITHUB_ENV
                fi
              done
              break
            fi
          done
          # Provide safe defaults if still unset (avoid Zod errors). These should be overridden if real values are decrypted later.
          : ${NEXT_PUBLIC_API_BASE_URL:=http://localhost}
          : ${NEXT_PUBLIC_NODE_ENV:=test}
          echo "NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_NODE_ENV=${NEXT_PUBLIC_NODE_ENV}" >> $GITHUB_ENV
          echo "Done preparing public env vars."

      # Step 2: Fast quality gates BEFORE docker build
      - name: Lint
        run: |
          if grep -q '"lint"' package.json; then
            echo "Running lint...";
            pnpm run lint || (echo 'Lint failed' && exit 1)
          else
            echo "No lint script found – skipping"
          fi

      - name: Type check
        run: |
          if [ -f tsconfig.json ]; then
            echo "Running TypeScript type check...";
            pnpm exec tsc --noEmit --pretty false
          else
            echo "No tsconfig.json – skipping type check"
          fi

      - name: Unit tests (Vitest)
        run: |
          set -e
          if grep -q 'vitest' package.json; then
            if pnpm exec vitest --version >/dev/null 2>&1; then
              echo "Running Vitest with JUnit + coverage reporters...";
              # Generate junit.xml, lcov.info and html report
              pnpm exec vitest run --reporter=default --reporter=junit --outputFile=junit.xml --coverage --coverage.reporter=lcov --coverage.reporter=html --run
            else
              echo "Vitest not installed? Ensure dependency is present."; exit 1
            fi
          elif grep -q '"test"' package.json; then
            echo "Running generic test script...";
            pnpm test -- --run || pnpm test
          else
            echo "No test framework detected – skipping tests"
          fi

      - name: Upload frontend test artifacts
        if: ${{ always() }}
        run: |
          set -e
          mkdir -p ci-artifacts/frontend
          [ -f junit.xml ] && cp junit.xml ci-artifacts/frontend/ || true
          [ -f coverage/lcov.info ] && cp coverage/lcov.info ci-artifacts/frontend/ || true
          if [ -d coverage ]; then tar -czf ci-artifacts/frontend/coverage-html.tar.gz coverage ; fi

      - name: Store frontend artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-and-coverage
          path: ci-artifacts/frontend
          if-no-files-found: ignore
          retention-days: 7

      - name: Annotate frontend test results
        if: ${{ always() && hashFiles('junit.xml') != '' }}
        uses: dorny/test-reporter@v1
        with:
          name: Frontend Tests
          path: junit.xml
          reporter: jest-junit
          fail-on-error: false

      - name: Frontend coverage summary
        if: ${{ always() }}
        run: |
          echo "## Frontend Test Summary" >> $GITHUB_STEP_SUMMARY
          if [ -f junit.xml ]; then
            TOTAL=$(grep -o 'tests="[0-9]\+"' junit.xml | head -1 | cut -d '"' -f2 || echo 0)
            FAIL=$(grep -o 'failures="[0-9]\+"' junit.xml | head -1 | cut -d '"' -f2 || echo 0)
            echo "Tests: $TOTAL, Failures: $FAIL" >> $GITHUB_STEP_SUMMARY
          else
            echo "No junit.xml produced" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -f coverage/lcov.info ]; then
            # Approximate line coverage: lines with hits / total lines instrumented
            COVERED_LINES=$(grep '^DA:' coverage/lcov.info | awk -F'[,:]' '$3>0{c++} END{print c+0}')
            TOTAL_LINES=$(grep '^DA:' coverage/lcov.info | wc -l | awk '{print $1+0}')
            if [ "$TOTAL_LINES" -gt 0 ]; then FRONTEND_COVERAGE_PERCENT=$(awk -v c=$COVERED_LINES -v t=$TOTAL_LINES 'BEGIN{printf("%.2f", (c/t)*100)}'); else FRONTEND_COVERAGE_PERCENT=0; fi
            echo "Coverage (line approx): ${FRONTEND_COVERAGE_PERCENT}% ($COVERED_LINES/$TOTAL_LINES)" >> $GITHUB_STEP_SUMMARY
            # Export for later steps
            echo "FRONTEND_COVERAGE_PERCENT=${FRONTEND_COVERAGE_PERCENT}" >> $GITHUB_ENV
          else
            echo "No coverage file" >> $GITHUB_STEP_SUMMARY
          fi

      # Decrypt only AFTER fast checks to reduce secret exposure window

      - name: Decrypt environment variables
        id: decrypt-env
        run: |
          echo "🔍 Checking for encrypted environment files..."

          # Setup cleanup trap for any exit (success or failure)
          cleanup() {
            echo "🧹 Performing security cleanup..."
            rm -f ./team-private-key.pem ./temp-aes-key ./.env ./next-public-build-args.txt
            echo "✅ Security cleanup completed"
          }
          trap cleanup EXIT

          # Find encrypted files in repository root
          ENCRYPTED_DATA=$(find . -maxdepth 1 -name "encrypted-env-vars.enc" -type f | head -1)
          ENCRYPTED_KEY=$(find . -maxdepth 1 -name "encrypted-aes-key.enc" -type f | head -1)
          METADATA=$(find . -maxdepth 1 -name "encrypted-env-vars.meta" -type f | head -1)

          if [[ -z "$ENCRYPTED_DATA" || -z "$ENCRYPTED_KEY" ]]; then
            echo "ℹ️ No encrypted environment files found - continuing without decryption"
            echo "has_encrypted_env=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "✅ Found encrypted files:"
          echo "  Data: $ENCRYPTED_DATA"
          echo "  Key: $ENCRYPTED_KEY"
          if [[ -n "$METADATA" ]]; then
            echo "  Metadata: $METADATA"
          fi
          echo "has_encrypted_env=true" >> $GITHUB_OUTPUT

          # Create private key from secret
          echo "🔑 Setting up private key for decryption..."
          echo "${{ secrets.TEAM_PRIVATE_KEY }}" > ./team-private-key.pem
          chmod 600 ./team-private-key.pem

          # Verify private key
          if ! openssl rsa -in ./team-private-key.pem -check -noout; then
            echo "❌ Invalid private key in TEAM_PRIVATE_KEY secret"
            exit 1
          fi
          echo "✅ Private key validated"

          # Show metadata if available (without sensitive content)
          if [[ -n "$METADATA" && -f "$METADATA" ]]; then
            echo "📋 Encryption Metadata:"
            echo "======================="
            cat "$METADATA"
            echo "======================="
          fi

          # Decrypt AES key
          echo "🔓 Decrypting AES key..."
          if ! openssl rsautl -decrypt \
            -inkey ./team-private-key.pem \
            -in "$ENCRYPTED_KEY" \
            -out ./temp-aes-key; then
            echo "❌ Failed to decrypt AES key"
            exit 1
          fi

          # Read AES key
          AES_KEY=$(cat ./temp-aes-key)

          # Decrypt data (try GCM first, then CBC)
          echo "🔓 Decrypting environment data..."
          if openssl enc -aes-256-gcm -d \
            -in "$ENCRYPTED_DATA" \
            -out "./.env" \
            -pass "pass:$AES_KEY" 2>/dev/null; then
            echo "✅ Decrypted with AES-GCM"
          elif openssl enc -aes-256-cbc -d \
            -in "$ENCRYPTED_DATA" \
            -out "./.env" \
            -pass "pass:$AES_KEY" 2>/dev/null; then
            echo "✅ Decrypted with AES-CBC"
          else
            echo "❌ Decryption failed with both AES-GCM and AES-CBC"
            exit 1
          fi

          # Verify decrypted content (without exposing content)
          if [[ -f "./.env" ]]; then
            LINES=$(wc -l < "./.env")
            SIZE=$(stat -c%s "./.env")
            echo "✅ Decryption completed successfully!"
            echo "📋 Decrypted .env file: $LINES lines, $SIZE bytes"
            echo "⚠️ Environment variables are available for build process only"
            
            # Ensure .env is not tracked by git
            # Add to .gitignore once (avoid duplicates across runs)
            grep -q '^\.env$' .gitignore 2>/dev/null || echo ".env" >> .gitignore
            git add .gitignore 2>/dev/null || true
          else
            echo "❌ Decrypted .env file not found"
            exit 1
          fi

      - name: Extract NEXT_PUBLIC environment variables
        id: extract-env
        if: steps.decrypt-env.outputs.has_encrypted_env == 'true'
        run: |
          echo "🔍 Extracting NEXT_PUBLIC_* environment variables..."

          if [[ ! -f "./.env" ]]; then
            echo "⚠️ No .env file found - skipping environment variable extraction"
            echo "has_next_public_vars=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Extract NEXT_PUBLIC_* variables (without exposing values in logs)
          NEXT_PUBLIC_VARS=$(grep '^NEXT_PUBLIC_' ./.env 2>/dev/null || true)

          if [[ -z "$NEXT_PUBLIC_VARS" ]]; then
            echo "ℹ️ No NEXT_PUBLIC_* variables found in .env file"
            echo "has_next_public_vars=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Count variables found (without showing values)
          VAR_COUNT=$(echo "$NEXT_PUBLIC_VARS" | wc -l)
          echo "✅ Found $VAR_COUNT NEXT_PUBLIC_* environment variables"
          echo "has_next_public_vars=true" >> $GITHUB_OUTPUT

          # Create build args string for Docker
          BUILD_ARGS=""
          echo "$NEXT_PUBLIC_VARS" | while IFS='=' read -r key value; do
            if [[ -n "$key" && -n "$value" ]]; then
              # Mask the value in logs for security
              echo "::add-mask::$value"
              echo "Found: $key=***MASKED***"
              
              # Append to build args (values will be masked in logs)
              if [[ -z "$BUILD_ARGS" ]]; then
                BUILD_ARGS="$key=$value"
              else
                BUILD_ARGS="$BUILD_ARGS"$'\n'"$key=$value"
              fi
            fi
          done

          # Save build args to output file (will be masked)
          echo "$NEXT_PUBLIC_VARS" > ./next-public-build-args.txt

          echo "🔒 Environment variables prepared for Docker build (values masked in logs)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Check for package.json
        run: |
          if [ ! -f "package.json" ]; then
            echo "❌ package.json not found"
            exit 1
          fi
          echo "✅ package.json found"

      - name: Check for required Next.js files
        run: |
          # Check for essential Next.js files
          if [ ! -f "next.config.js" ] && [ ! -f "next.config.mjs" ] && [ ! -f "next.config.ts" ]; then
            echo "⚠️ No Next.js config file found, using defaults"
          else
            echo "✅ Next.js configuration found"
          fi

          # Check for pages or app directory
          if [ ! -d "pages" ] && [ ! -d "app" ] && [ ! -d "src/pages" ] && [ ! -d "src/app" ]; then
            echo "❌ No pages or app directory found"
            exit 1
          fi
          echo "✅ Next.js routing structure verified"

      - name: Validate package.json scripts
        run: |
          # Verify required scripts exist
          REQUIRED_SCRIPTS=("build" "start")
          for script in "${REQUIRED_SCRIPTS[@]}"; do
            if ! grep -q "\"$script\":" package.json; then
              echo "❌ Required script '$script' not found in package.json"
              exit 1
            fi
          done
          echo "✅ Required npm scripts verified"

      # Step 3: Build Docker image only after fast checks succeed
      - name: Build multi-platform Docker image
        run: |
          echo "🏗️ Building Docker image with environment variables (post-tests)..."

          BUILD_CMD="docker buildx build --platform linux/amd64,linux/arm64"
          BUILD_CMD="$BUILD_CMD --cache-from type=gha --cache-to type=gha,mode=max"
          BUILD_CMD="$BUILD_CMD -t cloudinsight-frontend:latest -t cloudinsight-frontend:${{ github.sha }}"

          if [[ "${{ steps.extract-env.outputs.has_next_public_vars }}" == "true" && -f "./next-public-build-args.txt" ]]; then
            echo "🔒 Adding NEXT_PUBLIC_* environment variables as build arguments..."
            while IFS='=' read -r key value; do
              if [[ -n "$key" && -n "$value" ]]; then
                BUILD_CMD="$BUILD_CMD --build-arg $key=$value"
                echo "Added build arg: $key=***MASKED***"
              fi
            done < ./next-public-build-args.txt
          else
            echo "ℹ️ No NEXT_PUBLIC_* variables found - building without environment build args"
          fi

          BUILD_CMD="$BUILD_CMD ."
          echo "🚀 Executing Docker build..."
          eval "$BUILD_CMD"
          echo "✅ Docker image built successfully with environment variables"

      - name: Check for environment example
        run: |
          if [ -f ".env.example" ] || [ -f ".env.local.example" ]; then
            echo "✅ Environment example file found"
          else
            echo "⚠️ No .env.example file found (recommended for Next.js projects)"
          fi

      - name: Final validation
        run: |
          echo "🎉 All CI checks passed successfully!"
          echo "✅ Project structure validated"
          echo "✅ Multi-platform Docker image built"
          # Attempt to compute coverage percent again if env var not set
          if [ -z "$FRONTEND_COVERAGE_PERCENT" ] && [ -f coverage/lcov.info ]; then
            COVERED_LINES=$(grep '^DA:' coverage/lcov.info | awk -F'[,:]' '$3>0{c++} END{print c+0}')
            TOTAL_LINES=$(grep '^DA:' coverage/lcov.info | wc -l | awk '{print $1+0}')
            if [ "$TOTAL_LINES" -gt 0 ]; then FRONTEND_COVERAGE_PERCENT=$(awk -v c=$COVERED_LINES -v t=$TOTAL_LINES 'BEGIN{printf("%.2f", (c/t)*100)}'); else FRONTEND_COVERAGE_PERCENT=0; fi
          fi
          if [ -n "$FRONTEND_COVERAGE_PERCENT" ]; then
            echo "📊 Line coverage: ${FRONTEND_COVERAGE_PERCENT}%"; else echo "📊 Line coverage: n/a"; fi
          echo "✅ Ready for deployment / push (runtime container test skipped)"
          echo "ℹ️ Add runtime smoke tests later before push to registry"
